### ISSUE TITLE
improve documentation generation system

### ISSUE THREAD

**Issue by linsong** [linsong/sedona#18]
now sedona can parse kit files and generate api docs from it. But there are several drawbacks: 
* the comment in kit source file is just plain text, you can not use links or add styles to text 
* the comment spreads in kit source file, it is ok for reference about class, method etc. but it is not good for how-to kind of document

We can solve above issues by improving the doc parsing and processing script, and Markdown syntax will make the generated document more readable.  

Please add more possible improvements here.

**Comment by linsong** [comment]
I worked on documentation stuff recently in my project, after some research, I pick [asciidoctor](https://asciidoctor.org/) one variant of [asciidoc](http://asciidoc.org/). It is easy to highlight source code, convert to html or pdf, good diagram support, doc file inclusion for reuse, include portion of source code into document and much more. 

Github supports asciidoc format, here are some [examples](https://gist.github.com/dcode/0cfbf2699a1fe9b46ff04c41721dda74).

Maybe we can support writing docs using asciidoc instead of writing in html directly(seems only kit related docs are generated automatically, other docs are written in html directly, please correct me if I am wrong). We integrate the toolchain of asciidoctor into our doc generation script. 

I can help to convert the existing html docs into ascii format. After using asciidoctor for several days, I have converted all my docs into asciidoc format, believe me, you will love it, too :)

**Comment by divisuals** [comment]
Great thoughts and suggestions. I also evaluated various documentation stacks and settled on mkdocs for a few reasons:

- Besides the features with asciidocs, which were mostly at parity, mkdocs also has a powerful search feature, which can help any user search for a specific term or phrase in the published docs
- The starting point for mkdocs are markdown pages, which also render well in most editors and github as standalone pages. This would make the process of checking source files easier too
- The stack allows for publishing directly to github (I could use your help on this one!)
- Finally, the stack is based on python modules, which lines-up well with existing sedona tooling. Asciidoctor would require additional _ruby_ setup as well, adding to dependencies

I already started the process of converting the documents (HTML -> MD) on the **new_docs** branch. I'm not deleting older HTML files per se, just creating an MD-equivalent file for it. The big change would be in `WriteDocs.java` (sedonac) which currently parses sedona files and creates static HTML files. Shouldn't be terribly hard to change the output to MD.

If you still feel strongly about using asciidoctor, let me know soon so that we can discuss alternate plans!

**Comment by divisuals** [comment]
Yup, there are tonnes of frameworks here - I personally used middleman and [doctor](https://github.com/minio/doctor) which is not even listed :)

Thanks for pandoc - will save me a lot of time ~ 80-90% conversion of the page is good! Just need to fix the links. Hopefully, will get to the pull-request stage by end of the week!

**Comment by AndreySV** [comment]
https://linsong.github.io/sedona/doc/sys/index.html
API documentation is not available anymore on github-pages.
@divisuals , are your changes related to this problem?

**Comment by linsong** [comment]
I think I know why this happens. I will fix it tonight.

**Comment by linsong** [comment]
@AndreySV The doc web page should be ok now.

**Comment by AndreySV** [comment]
Thanks.

**Comment by divisuals** [comment]
Picking-up this again after a gap. I have a branch `new_docs` from develop for this work. 

Any suggestions how to get it refreshed to the latest (`master`) version?

**Comment by linsong** [comment]
this comment should be helpful: https://github.com/linsong/sedona/issues/38#issuecomment-489310062
